Make curl command/path configurable

diff --git a/wcofun b/wcofun
--- a/wcofun
+++ b/wcofun
@@ -21,11 +21,16 @@ else
 # User agent. Maybe you have problems with this
 UA="User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
 
+# Use system's curl by default
+CURL_PATH=$(which curl)
+
 # Maybe you want to use a proxy? (Helps when getting blocked by cloudflare, or if you want to debug)
 CURL_EXTRA_PARAMS=""
 # CURL_EXTRA_PARAMS="-k --tlsv1 -x http://localhost:8080"
 PRE_COMMAND=""
 # PRE_COMMAND="mitmdump 2>&1 /dev/null"
+
+##########################################################################################
 
 # if the config file exists, it will override the variables above
 if [ -f ~/.wcofunrc ]
@@ -34,7 +39,11 @@ then
   source ~/.wcofunrc
 fi
 
-##########################################################################################
+if [ -z "$CURL_PATH" ]
+then
+  echo "curl executable not found. You need to set CURL_PATH or install curl"
+  exit 1
+fi
 
 baseurl="https://www.wcofun.com/"
 domainname="www.wcofun.com"
@@ -116,7 +125,7 @@ chru() { printf "\x$(printf %x "$1")"; }
 get_link() {
   link=$1
   script=$(
-  curl --silent $CURL_EXTRA_PARAMS "$link" -H "$UA" --compressed | htmlq 'body > div:nth-child(3) > div.twelve.columns > div > div.fourteen.columns > div:nth-child(7) > script:nth-child(2)' | sed 's/<script>\(.*\)<\/script>/\1/')
+  "$CURL_PATH" --silent $CURL_EXTRA_PARAMS "$link" -H "$UA" --compressed | htmlq 'body > div:nth-child(3) > div.twelve.columns > div > div.fourteen.columns > div:nth-child(7) > script:nth-child(2)' | sed 's/<script>\(.*\)<\/script>/\1/')
   offset=$(echo "$script" | sed 's/.*- \([0-9]*\).*).*/\1/')
 
   innerscript=$(
@@ -128,9 +137,9 @@ get_link() {
   )
 
   url=$baseurl$(echo "$innerscript" | sed 's/^.*src="\([^"]*\)".*$/\1/')
-  url=$baseurl$(curl --silent $CURL_EXTRA_PARAMS "$url" -H "$UA" | grep "$.getJSON" | sed 's/^.*"\(.*\)".*$/\1/')
+  url=$baseurl$("$CURL_PATH" --silent $CURL_EXTRA_PARAMS "$url" -H "$UA" | grep "$.getJSON" | sed 's/^.*"\(.*\)".*$/\1/')
 
-  curl --silent $CURL_EXTRA_PARAMS  "$url" \
+  "$CURL_PATH" --silent $CURL_EXTRA_PARAMS  "$url" \
     -H "authority: $domainname" \
     -H 'pragma: no-cache' \
     -H 'cache-control: no-cache' \
@@ -151,7 +160,7 @@ get_num() {
 }
 
 download () {
-  curl "$1" \
+  "$CURL_PATH" "$1" \
     -H 'Connection: keep-alive' \
     -H "$UA" \
     -H 'Accept: */*' \
@@ -169,7 +178,7 @@ download () {
 }
 
 stream () {
-  curl "$1" \
+  "$CURL_PATH" "$1" \
     -H 'Connection: keep-alive' \
     -H "$UA" \
     -H 'Accept: */*' \
@@ -188,7 +197,7 @@ stream () {
 
 search () {
   list=$(
-    curl --silent $CURL_EXTRA_PARAMS "$baseurl/search" \
+    "$CURL_PATH" --silent $CURL_EXTRA_PARAMS "$baseurl/search" \
     -X POST -H "$UA" \
     -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
     -H 'Accept-Language: en-US,en;q=0.5' \
@@ -232,7 +241,7 @@ search () {
 }
 
 choose_ep () {
-  list=$(curl --silent $CURL_EXTRA_PARAMS "$1" \
+  list=$("$CURL_PATH" --silent $CURL_EXTRA_PARAMS "$1" \
   -H "authority: $domainname" \
   -H 'pragma: no-cache' \
   -H 'cache-control: no-cache' \
@@ -274,7 +283,7 @@ choose_ep () {
 }
 
 all_eps () {
-  curl --silent $CURL_EXTRA_PARAMS "$1" \
+  "$CURL_PATH" --silent $CURL_EXTRA_PARAMS "$1" \
   -H "authority: $domainname" \
   -H 'pragma: no-cache' \
   -H 'cache-control: no-cache' \
